workflows:
  build-apk:
    name: Rabbit

environment:
  node: 22
  java: 17

 scripts:
      - name: Force Java 17
        script: |
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
      java -version

    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          
      - name: install capacitor
        script: |
         npm install @capacitor/android@5 @capacitor/core@5 @capacitor/cli@5

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
